version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - .:/app/
    ports:
      - "3000:3000"

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
    - ./data:/data/db
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
    - '27017:27017'